import { apiTarihi, formTarihi, metinYaDaNull } from "./yardimcilar";

/*
 * Ekipman karti formu: alan adlari, GetMakineById -> form ve form -> UpdateMakine donusumleri.
 * Alan adlari ve UpdateMakine govdesi eski Ekipman Sicil Karti (MakineTanim/EditDrawer.jsx) ile aynidir;
 * tasarimla gelen Arac (MKN_ARAC) ve Proje (MKN_PROJE_ID) alanlari eklenmistir.
 * KodID alanlarinda gorunen alan etiketi, `...ID` alani numerik ID'yi tutar (RULES kural 10).
 */

/** Ozel alan 11-15 kod listesi alanlaridir (etiket + ID). */
const KOD_LISTELI_OZEL_ALANLAR = [11, 12, 13, 14, 15];
const OZEL_ALAN_NUMARALARI = Array.from({ length: 20 }, (_, index) => index + 1);

/** Ruhsat alanlari (Arac sekmesi). Arac sekmesi acilinca GetAracRuhsatByMakineId ile doldurulur. */
const RUHSAT_VARSAYILANLARI = {
  aracId: null,
  ruhsatYuklendi: false,
  ruhsatPlaka: null,
  ruhsatSahip: null,
  ruhsatSahipID: null,
  ruhsatAracSinifi: null,
  ruhsatIl: null,
  ruhsatIlID: null,
  ruhsatIlce: null,
  ruhsatIlceID: null,
  ruhsatBelgeSeriNo: null,
  ruhsatTescilNo: null,
  ruhsatTescilTarihi: null,
  ruhsatIlkTescilTarihi: null,
  ruhsatTicariAdi: null,
  ruhsatAracCinsi: null,
  ruhsatAracCinsiID: null,
  ruhsatKullanimAmaci: null,
  ruhsatIstiapHaddi: null,
  ruhsatRomorkIstiapHaddi: null,
  ruhsatKoltukSayisi: null,
  ruhsatAyaktaYolcuSayisi: null,
  muayeneTarihi: null,
  muayeneKalanGun: null,
  egzozTarihi: null,
  egzozKalanGun: null,
  vergiTarihi: null,
  vergiKalanGun: null,
  sozlesmeTarihi: null,
};

export const VARSAYILAN_DEGERLER = {
  makineId: null,
  // Genel bilgiler
  makineKodu: null,
  makineTanimi: null,
  lokasyon: null,
  lokasyonID: null,
  makineTipi: null,
  makineTipiID: null,
  kategori: null,
  kategoriID: null,
  operator: null,
  operatorID: null,
  marka: null,
  markaID: null,
  model: null,
  modelID: null,
  operasyonDurumu: null,
  operasyonDurumuID: null,
  operasyonDurumuText: null,
  seriNo: null,
  masterMakine: null,
  masterMakineID: null,
  proje: null,
  projeID: null,
  takvim: null,
  takvimID: null,
  uretici: null,
  uretimYili: null,
  garantiBitisTarihi: null,
  durusBirimMaliyeti: null,
  planCalismaSuresi: null,
  // Durum & ozellikler
  makineAktif: false,
  makineKalibrasyon: false,
  kritikMakine: false,
  makineGucKaynagi: false,
  makineIsBildirimi: false,
  makineOtonomBakim: false,
  makineYakitKullanim: false,
  arac: false,
  // Detay bilgi
  masrafMerkeziDetay: null,
  masrafMerkeziIDDetay: null,
  atolyeTanim: null,
  atolyeID: null,
  bakimGrubu: null,
  bakimGrubuID: null,
  arizaGrubu: null,
  arizaGrubuID: null,
  servisSaglayici: null,
  servisSaglayiciID: null,
  servisSekli: null,
  servisSekliID: null,
  teknikSeviyesi: null,
  teknikSeviyesiID: null,
  fizikselDurumu: null,
  fizikselDurumuID: null,
  oncelikDetay: null,
  oncelikIDDetay: null,
  riskPuani: null,
  kurulumTarihi: null,
  isletimSistemi: null,
  isletimSistemiID: null,
  ipNo: null,
  agirlik: null,
  agirlikBirim: null,
  agirlikBirimID: null,
  hacim: null,
  hacimBirim: null,
  hacimBirimID: null,
  kapasite: null,
  kapasiteBirim: null,
  kapasiteBirimID: null,
  elektrikTuketimi: null,
  elektrikTuketimiBirim: null,
  elektrikTuketimiBirimID: null,
  voltaj: null,
  guc: null,
  faz: null,
  valfTipi: null,
  valfTipiID: null,
  valfBoyutu: null,
  valfBoyutuID: null,
  girisBoyutu: null,
  girisBoyutuID: null,
  cikisBoyutu: null,
  cikisBoyutuID: null,
  konnektor: null,
  konnektorID: null,
  makineBasinc: null,
  makineBasincID: null,
  basincMiktar: null,
  basincMiktarBirim: null,
  basincMiktarBirimID: null,
  devirSayisi: null,
  motorGucu: null,
  silindirSayisi: null,
  // Finansal bilgiler
  satinalmaFirma: null,
  satinalmaFirmaID: null,
  faturaNo: null,
  satinalmaTarihi: null,
  faturaTarihi: null,
  satinalmaFiyati: null,
  faturaTutari: null,
  krediMiktari: null,
  krediBaslamaTarihi: null,
  krediOrani: null,
  krediBitisTarihi: null,
  kiralik: false,
  kiralikFirma: null,
  kiralikFirmaID: null,
  kiraBaslangicTarihi: null,
  kiraBitisTarihi: null,
  kiraSuresi: null,
  kiraSuresiBirim: null,
  kiraSuresiBirimID: null,
  kiraTutari: null,
  kiraAciklama: null,
  satildi: false,
  satisNedeni: null,
  satisTarihi: null,
  satisYeri: null,
  satisTutari: null,
  satisAciklama: null,
  // Yakit bilgileri
  makineYakitTipi: null,
  makineYakitTipiID: null,
  YakitDepoHacmi: null,
  makineYakitSayacTakibi: false,
  makineYakitSayacGuncellemesi: false,
  ongorulenMin: null,
  ongorulenMax: null,
  gerceklesen: null,
  // Ozel alanlar (11-15 icin ayrica ...ID)
  ...Object.fromEntries(OZEL_ALAN_NUMARALARI.map((no) => [`ozelAlan${no}`, null])),
  ...Object.fromEntries(KOD_LISTELI_OZEL_ALANLAR.map((no) => [`ozelAlan${no}ID`, null])),
  // Notlar
  makineGenelNot: null,
  makineGuvenlikNotu: null,
  ...RUHSAT_VARSAYILANLARI,
};

/** GetMakineById kaydi -> form degerleri (reset ile yazilir). */
export const makineFormDegerleri = (kayit) => ({
  ...VARSAYILAN_DEGERLER,
  makineId: kayit.TB_MAKINE_ID ?? null,
  makineKodu: metinYaDaNull(kayit.MKN_KOD),
  makineTanimi: metinYaDaNull(kayit.MKN_TANIM),
  lokasyon: metinYaDaNull(kayit.MKN_LOKASYON),
  lokasyonID: kayit.MKN_LOKASYON_ID ?? null,
  makineTipi: metinYaDaNull(kayit.MKN_TIP),
  makineTipiID: kayit.MKN_TIP_KOD_ID ?? null,
  kategori: metinYaDaNull(kayit.MKN_KATEGORI),
  kategoriID: kayit.MKN_KATEGORI_KOD_ID ?? null,
  operator: metinYaDaNull(kayit.MKN_OPERATOR),
  operatorID: kayit.MKN_OPERATOR_PERSONEL_ID ?? null,
  marka: metinYaDaNull(kayit.MKN_MARKA),
  markaID: kayit.MKN_MARKA_KOD_ID ?? null,
  model: metinYaDaNull(kayit.MKN_MODEL),
  modelID: kayit.MKN_MODEL_KOD_ID ?? null,
  operasyonDurumu: metinYaDaNull(kayit.MKN_DURUM),
  operasyonDurumuID: kayit.MKN_DURUM_KOD_ID ?? null,
  operasyonDurumuText: metinYaDaNull(kayit.MKN_DURUM),
  seriNo: metinYaDaNull(kayit.MKN_SERI_NO),
  masterMakine: metinYaDaNull(kayit.MKN_MASTER_MAKINE_TANIM),
  masterMakineID: kayit.MKN_MASTER_ID ?? null,
  proje: metinYaDaNull(kayit.MKN_PROJE),
  projeID: kayit.MKN_PROJE_ID ?? null,
  takvim: metinYaDaNull(kayit.MKN_TAKVIM),
  takvimID: kayit.MKN_TAKVIM_ID ?? null,
  uretici: metinYaDaNull(kayit.MKN_URETICI),
  uretimYili: formTarihi(kayit.MKN_URETIM_YILI, "YYYY"),
  garantiBitisTarihi: formTarihi(kayit.MKN_GARANTI_BITIS),
  durusBirimMaliyeti: kayit.MKN_DURUS_MALIYET ?? null,
  planCalismaSuresi: kayit.MKN_YILLIK_PLANLANAN_CALISMA_SURESI ?? null,
  makineAktif: Boolean(kayit.MKN_AKTIF),
  makineKalibrasyon: Boolean(kayit.MKN_KALIBRASYON_VAR),
  kritikMakine: Boolean(kayit.MKN_KRITIK_MAKINE),
  makineGucKaynagi: Boolean(kayit.MKN_GUC_KAYNAGI),
  makineIsBildirimi: Boolean(kayit.MKN_IS_TALEP),
  makineOtonomBakim: Boolean(kayit.MKN_OTONOM_BAKIM),
  makineYakitKullanim: Boolean(kayit.MKN_YAKIT_KULLANIM),
  arac: Boolean(kayit.MKN_ARAC),
  masrafMerkeziDetay: metinYaDaNull(kayit.MKN_MASRAF_MERKEZ),
  masrafMerkeziIDDetay: kayit.MKN_MASRAF_MERKEZ_KOD_ID ?? null,
  atolyeTanim: metinYaDaNull(kayit.MKN_ATOLYE),
  atolyeID: kayit.MKN_ATOLYE_ID ?? null,
  bakimGrubu: metinYaDaNull(kayit.MKN_BAKIM_GRUP),
  bakimGrubuID: kayit.MKN_BAKIM_GRUP_ID ?? null,
  arizaGrubu: metinYaDaNull(kayit.MKN_ARIZA_GRUP),
  arizaGrubuID: kayit.MKN_ARIZA_GRUP_ID ?? null,
  servisSaglayici: metinYaDaNull(kayit.MKN_SERVIS_SAGLAYICI),
  servisSaglayiciID: kayit.MKN_SERVIS_SAGLAYICI_KOD_ID ?? null,
  servisSekli: metinYaDaNull(kayit.MKN_SERVIS_SEKLI),
  servisSekliID: kayit.MKN_SERVIS_SEKLI_KOD_ID ?? null,
  teknikSeviyesi: metinYaDaNull(kayit.MKN_TEKNIK_SERVIS),
  teknikSeviyesiID: kayit.MKN_TEKNIK_SERVIS_KOD_ID ?? null,
  fizikselDurumu: metinYaDaNull(kayit.MKN_FIZIKSEL_DURUM),
  fizikselDurumuID: kayit.MKN_FIZIKSEL_DURUM_KOD_ID ?? null,
  oncelikDetay: metinYaDaNull(kayit.MKN_ONCELIK),
  oncelikIDDetay: kayit.MKN_ONCELIK_ID ?? null,
  riskPuani: metinYaDaNull(kayit.MKN_RISK_PUAN),
  kurulumTarihi: formTarihi(kayit.MKN_KURULUM_TARIH),
  isletimSistemi: metinYaDaNull(kayit.MKN_ISLETIM_SISTEMI),
  isletimSistemiID: kayit.MKN_ISLETIM_SISTEMI_KOD_ID ?? null,
  ipNo: metinYaDaNull(kayit.MKN_IP_NO),
  agirlik: kayit.MKN_AGIRLIK ?? null,
  agirlikBirim: metinYaDaNull(kayit.MKN_AGIRLIK_BIRIM),
  agirlikBirimID: kayit.MKN_AGIRLIK_BIRIM_KOD_ID ?? null,
  hacim: kayit.MKN_HACIM ?? null,
  hacimBirim: metinYaDaNull(kayit.MKN_HACIM_BIRIM),
  hacimBirimID: kayit.MKN_HACIM_BIRIM_KOD_ID ?? null,
  kapasite: metinYaDaNull(kayit.MKN_KAPASITE),
  kapasiteBirim: metinYaDaNull(kayit.MKN_KAPASITE_BIRIM),
  kapasiteBirimID: kayit.MKN_KAPASITE_BIRIM_KOD_ID ?? null,
  elektrikTuketimi: metinYaDaNull(kayit.MKN_ELEKTRIK_TUKETIM),
  elektrikTuketimiBirim: metinYaDaNull(kayit.MKN_ELEKTRIK_TUKETIM_BIRIM),
  elektrikTuketimiBirimID: kayit.MKN_ELEKTRIK_TUKETIM_BIRIM_KOD_ID ?? null,
  voltaj: metinYaDaNull(kayit.MKN_VOLTAJ),
  guc: metinYaDaNull(kayit.MKN_GUC),
  faz: metinYaDaNull(kayit.MKN_FAZ),
  valfTipi: metinYaDaNull(kayit.MKN_VALF_TIPI),
  valfTipiID: kayit.MKN_VALF_TIP_KOD_ID ?? null,
  valfBoyutu: metinYaDaNull(kayit.MKN_VALF_BOYUT),
  valfBoyutuID: kayit.MKN_VALF_BOYUT_KOD_ID ?? null,
  girisBoyutu: metinYaDaNull(kayit.MKN_GIRIS_BOYUT),
  girisBoyutuID: kayit.MKN_GIRIS_BOYUT_KOD_ID ?? null,
  cikisBoyutu: metinYaDaNull(kayit.MKN_CIKIS_BOYUT),
  cikisBoyutuID: kayit.MKN_CIKIS_BOYUT_KOD_ID ?? null,
  konnektor: metinYaDaNull(kayit.MKN_KONNEKTOR),
  konnektorID: kayit.MKN_KONNEKTOR_KOD_ID ?? null,
  makineBasinc: metinYaDaNull(kayit.MKN_BASINC),
  makineBasincID: kayit.MKN_BASINC_KOD_ID ?? null,
  basincMiktar: kayit.MKN_BASINC_MIKTAR ?? null,
  basincMiktarBirim: metinYaDaNull(kayit.MKN_BASINC_BIRIM),
  basincMiktarBirimID: kayit.MKN_BASINC_BIRIM_KOD_ID ?? null,
  devirSayisi: kayit.MKN_DEVIR ?? null,
  motorGucu: metinYaDaNull(kayit.MKN_TEKNIK_MOTOR_GUCU),
  silindirSayisi: metinYaDaNull(kayit.MKN_TEKNIK_SILINDIR_SAYISI),
  satinalmaFirma: metinYaDaNull(kayit.MKN_ALIS_FIRMA),
  satinalmaFirmaID: kayit.MKN_ALIS_FIRMA_ID ?? null,
  satinalmaTarihi: formTarihi(kayit.MKN_ALIS_TARIH),
  satinalmaFiyati: kayit.MKN_ALIS_FIYAT ?? null,
  faturaNo: metinYaDaNull(kayit.MKN_FATURA_NO),
  faturaTarihi: formTarihi(kayit.MKN_FATURA_TARIH),
  faturaTutari: kayit.MKN_FATURA_TUTAR ?? null,
  krediMiktari: kayit.MKN_KREDI_MIKTARI ?? null,
  krediOrani: kayit.KREDI_ORANI ?? null,
  krediBaslamaTarihi: formTarihi(kayit.MKN_KREDI_BASLAMA_TARIHI),
  krediBitisTarihi: formTarihi(kayit.MKN_KREDI_BITIS_TARIHI),
  kiralik: Boolean(kayit.MKN_KIRA),
  kiralikFirma: metinYaDaNull(kayit.MKN_KIRA_FIRMA),
  kiralikFirmaID: kayit.MKN_KIRA_FIRMA_ID ?? null,
  kiraBaslangicTarihi: formTarihi(kayit.MKN_KIRA_BASLANGIC_TARIH),
  kiraBitisTarihi: formTarihi(kayit.MKN_KIRA_BITIS_TARIH),
  kiraSuresi: kayit.MKN_KIRA_SURE ?? null,
  kiraSuresiBirim: metinYaDaNull(kayit.MKN_KIRA_PERIYOD),
  kiraSuresiBirimID: kayit.MKN_KIRA_SURE_BIRIM_KOD_ID ?? null,
  kiraTutari: kayit.MKN_KIRA_TUTAR ?? null,
  kiraAciklama: metinYaDaNull(kayit.MKN_KIRA_ACIKLAMA),
  satildi: Boolean(kayit.MKN_SATIS),
  satisNedeni: metinYaDaNull(kayit.MKN_SATIS_NEDEN),
  satisTarihi: formTarihi(kayit.MKN_SATIS_TARIH),
  satisYeri: metinYaDaNull(kayit.MKN_SATIS_YER),
  satisTutari: kayit.MKN_SATIS_FIYAT ?? null,
  satisAciklama: metinYaDaNull(kayit.MKN_SATIS_ACIKLAMA),
  makineYakitTipi: metinYaDaNull(kayit.MKN_YAKIT_TIPI),
  makineYakitTipiID: kayit.MKN_YAKIT_TIP_ID ?? null,
  YakitDepoHacmi: kayit.MKN_YAKIT_DEPO_HACMI ?? null,
  makineYakitSayacTakibi: Boolean(kayit.MKN_YAKIT_SAYAC_TAKIP),
  makineYakitSayacGuncellemesi: Boolean(kayit.MKN_YAKIT_SAYAC_GUNCELLE),
  ongorulenMin: kayit.MKN_YAKIT_ONGORULEN_MIN ?? null,
  ongorulenMax: kayit.MKN_YAKIT_ONGORULEN_MAX ?? null,
  gerceklesen: kayit.MKN_YAKIT_GERCEKLESEN ?? null,
  ...Object.fromEntries(OZEL_ALAN_NUMARALARI.map((no) => [`ozelAlan${no}`, metinYaDaNull(kayit[`MKN_OZEL_ALAN_${no}`])])),
  ...Object.fromEntries(KOD_LISTELI_OZEL_ALANLAR.map((no) => [`ozelAlan${no}ID`, kayit[`MKN_OZEL_ALAN_${no}_KOD_ID`] ?? null])),
  makineGenelNot: metinYaDaNull(kayit.MKN_GENEL_NOT),
  makineGuvenlikNotu: metinYaDaNull(kayit.MKN_GUVENLIK_NOT),
});

const yilMetni = (deger) => {
  const tarih = formTarihi(deger);
  return tarih ? tarih.format("YYYY") : "";
};

/** Form -> UpdateMakine govdesi (eski kartla ayni alanlar + MKN_ARAC, MKN_PROJE_ID). */
export const makineGuncellemeGovdesi = (veri) => ({
  TB_MAKINE_ID: veri.makineId,
  MKN_KOD: veri.makineKodu,
  MKN_TANIM: veri.makineTanimi,
  MKN_LOKASYON_ID: veri.lokasyonID,
  MKN_TIP_KOD_ID: veri.makineTipiID,
  MKN_KATEGORI_KOD_ID: veri.kategoriID,
  MKN_MARKA_KOD_ID: veri.markaID,
  MKN_MODEL_KOD_ID: veri.modelID,
  MKN_OPERATOR_PERSONEL_ID: veri.operatorID,
  MKN_DURUM_KOD_ID: veri.operasyonDurumuID,
  MKN_SERI_NO: veri.seriNo,
  MKN_MASTER_ID: veri.masterMakineID,
  MKN_PROJE_ID: veri.projeID,
  MKN_TAKVIM_ID: veri.takvimID,
  MKN_URETICI: veri.uretici,
  MKN_URETIM_YILI: yilMetni(veri.uretimYili),
  MKN_GARANTI_BITIS: apiTarihi(veri.garantiBitisTarihi) ?? "",
  MKN_DURUS_MALIYET: veri.durusBirimMaliyeti,
  MKN_YILLIK_PLANLANAN_CALISMA_SURESI: veri.planCalismaSuresi,
  MKN_AKTIF: veri.makineAktif,
  MKN_KALIBRASYON_VAR: veri.makineKalibrasyon,
  MKN_KRITIK_MAKINE: veri.kritikMakine,
  MKN_GUC_KAYNAGI: veri.makineGucKaynagi,
  MKN_IS_TALEP: veri.makineIsBildirimi,
  MKN_YAKIT_KULLANIM: veri.makineYakitKullanim,
  MKN_OTONOM_BAKIM: veri.makineOtonomBakim,
  MKN_ARAC: veri.arac,
  MKN_MASRAF_MERKEZ_KOD_ID: veri.masrafMerkeziIDDetay,
  MKN_ATOLYE_ID: veri.atolyeID,
  MKN_BAKIM_GRUP_ID: veri.bakimGrubuID,
  MKN_ARIZA_GRUP_ID: veri.arizaGrubuID,
  MKN_SERVIS_SAGLAYICI_KOD_ID: veri.servisSaglayiciID,
  MKN_SERVIS_SEKLI_KOD_ID: veri.servisSekliID,
  MKN_TEKNIK_SERVIS_KOD_ID: veri.teknikSeviyesiID,
  MKN_FIZIKSEL_DURUM_KOD_ID: veri.fizikselDurumuID,
  MKN_ONCELIK_ID: veri.oncelikIDDetay,
  MKN_RISK_PUAN: veri.riskPuani,
  MKN_KURULUM_TARIH: apiTarihi(veri.kurulumTarihi) ?? "",
  MKN_ISLETIM_SISTEMI_KOD_ID: veri.isletimSistemiID,
  MKN_IP_NO: veri.ipNo,
  MKN_AGIRLIK: veri.agirlik,
  MKN_AGIRLIK_BIRIM_KOD_ID: veri.agirlikBirimID,
  MKN_HACIM: veri.hacim,
  MKN_HACIM_BIRIM_KOD_ID: veri.hacimBirimID,
  MKN_KAPASITE: veri.kapasite,
  MKN_KAPASITE_BIRIM_KOD_ID: veri.kapasiteBirimID,
  MKN_ELEKTRIK_TUKETIM: veri.elektrikTuketimi,
  MKN_ELEKTRIK_TUKETIM_BIRIM_KOD_ID: veri.elektrikTuketimiBirimID,
  MKN_VOLTAJ: veri.voltaj,
  MKN_GUC: veri.guc,
  MKN_FAZ: veri.faz,
  MKN_VALF_TIP_KOD_ID: veri.valfTipiID,
  MKN_VALF_BOYUT_KOD_ID: veri.valfBoyutuID,
  MKN_GIRIS_BOYUT_KOD_ID: veri.girisBoyutuID,
  MKN_CIKIS_BOYUT_KOD_ID: veri.cikisBoyutuID,
  MKN_KONNEKTOR_KOD_ID: veri.konnektorID,
  MKN_BASINC_KOD_ID: veri.makineBasincID,
  MKN_BASINC_MIKTAR: veri.basincMiktar,
  MKN_BASINC_BIRIM_KOD_ID: veri.basincMiktarBirimID,
  MKN_DEVIR: veri.devirSayisi,
  MKN_TEKNIK_MOTOR_GUCU: veri.motorGucu,
  MKN_TEKNIK_SILINDIR_SAYISI: veri.silindirSayisi,
  MKN_ALIS_FIRMA_ID: veri.satinalmaFirmaID,
  MKN_ALIS_TARIH: apiTarihi(veri.satinalmaTarihi) ?? "",
  MKN_ALIS_FIYAT: veri.satinalmaFiyati,
  MKN_FATURA_NO: veri.faturaNo,
  MKN_FATURA_TARIH: apiTarihi(veri.faturaTarihi) ?? "",
  MKN_FATURA_TUTAR: veri.faturaTutari,
  MKN_KREDI_MIKTARI: veri.krediMiktari,
  KREDI_ORANI: veri.krediOrani,
  MKN_KREDI_BASLAMA_TARIHI: apiTarihi(veri.krediBaslamaTarihi) ?? "",
  MKN_KREDI_BITIS_TARIHI: apiTarihi(veri.krediBitisTarihi) ?? "",
  MKN_KIRA: veri.kiralik,
  MKN_KIRA_FIRMA_ID: veri.kiralikFirmaID,
  MKN_KIRA_BASLANGIC_TARIH: apiTarihi(veri.kiraBaslangicTarihi) ?? "",
  MKN_KIRA_BITIS_TARIH: apiTarihi(veri.kiraBitisTarihi) ?? "",
  MKN_KIRA_SURE: veri.kiraSuresi,
  // Eski kartta oldugu gibi birim metni gonderilir (KodIDSelectbox secimden sonra alana ID yazar).
  MKN_KIRA_PERIYOD: veri.kiraSuresiBirim ? (veri.kiraSuresiBirim.label ?? veri.kiraSuresiBirim) : null,
  MKN_KIRA_TUTAR: veri.kiraTutari,
  MKN_KIRA_ACIKLAMA: veri.kiraAciklama,
  MKN_SATIS: veri.satildi,
  MKN_SATIS_NEDEN: veri.satisNedeni,
  MKN_SATIS_TARIH: apiTarihi(veri.satisTarihi) ?? "",
  MKN_SATIS_YER: veri.satisYeri,
  MKN_SATIS_FIYAT: veri.satisTutari,
  MKN_SATIS_ACIKLAMA: veri.satisAciklama,
  MKN_YAKIT_TIP_ID: veri.makineYakitTipiID,
  MKN_YAKIT_DEPO_HACMI: veri.YakitDepoHacmi,
  MKN_YAKIT_SAYAC_TAKIP: veri.makineYakitSayacTakibi,
  MKN_YAKIT_SAYAC_GUNCELLE: veri.makineYakitSayacGuncellemesi,
  MKN_YAKIT_ONGORULEN_MIN: veri.ongorulenMin,
  MKN_YAKIT_ONGORULEN_MAX: veri.ongorulenMax,
  MKN_YAKIT_GERCEKLESEN: veri.gerceklesen,
  ...Object.fromEntries(
    OZEL_ALAN_NUMARALARI.map((no) =>
      KOD_LISTELI_OZEL_ALANLAR.includes(no) ? [`MKN_OZEL_ALAN_${no}_KOD_ID`, veri[`ozelAlan${no}ID`]] : [`MKN_OZEL_ALAN_${no}`, veri[`ozelAlan${no}`]]
    )
  ),
  MKN_GUVENLIK_NOT: veri.makineGuvenlikNotu,
  MKN_GENEL_NOT: veri.makineGenelNot,
});

/** GetAracRuhsatByMakineId kaydi -> ruhsat alanlari. */
export const ruhsatFormDegerleri = (kayit) => ({
  aracId: kayit.TB_ARAC_ID ?? null,
  ruhsatYuklendi: true,
  ruhsatPlaka: metinYaDaNull(kayit.ARC_PLAKA),
  ruhsatSahip: metinYaDaNull(kayit.ARC_RUHSAT_SAHIP),
  ruhsatSahipID: kayit.ARC_RUHSAT_SAHIP_KOD_ID ?? null,
  ruhsatAracSinifi: metinYaDaNull(kayit.ARC_RUHSAT_ARAC_SINIFI),
  ruhsatIl: metinYaDaNull(kayit.ARC_RUHSAT_IL),
  ruhsatIlID: kayit.ARC_RUHSAT_IL_ID ?? null,
  ruhsatIlce: metinYaDaNull(kayit.ARC_RUHSAT_ILCE),
  ruhsatIlceID: kayit.ARC_RUHSAT_ILCE_ID ?? null,
  ruhsatBelgeSeriNo: metinYaDaNull(kayit.ARC_RUHSAT_BELGE_SERI_NO),
  ruhsatTescilNo: metinYaDaNull(kayit.ARC_RUHSAT_TESCIL_NO),
  ruhsatTescilTarihi: formTarihi(kayit.ARC_RUHSAT_TESCIL_TARIH),
  ruhsatIlkTescilTarihi: formTarihi(kayit.ARC_RUHSAT_TRAFIK_CIKIS_TARIH),
  ruhsatTicariAdi: metinYaDaNull(kayit.ARC_RUHSAT_TICARI_ADI),
  ruhsatAracCinsi: metinYaDaNull(kayit.ARC_RUHSAT_ARAC_CINS),
  ruhsatAracCinsiID: kayit.ARC_RUHSAT_ARAC_CINSI_KOD_ID ?? null,
  ruhsatKullanimAmaci: metinYaDaNull(kayit.ARC_RUHSAT_KULLANIM_AMACI),
  ruhsatIstiapHaddi: metinYaDaNull(kayit.ARC_RUHSAT_ISTIAP_HADDI),
  ruhsatRomorkIstiapHaddi: metinYaDaNull(kayit.ARC_RUHSAT_ROMORK_ISTIAP_HADDI),
  ruhsatKoltukSayisi: metinYaDaNull(kayit.ARC_RUHSAT_KOLTUK_SAYISI),
  ruhsatAyaktaYolcuSayisi: metinYaDaNull(kayit.ARC_RUHSAT_AYAKTA_YOLCU_SAYISI),
  muayeneTarihi: formTarihi(kayit.ARC_MUAYENE_TARIH),
  muayeneKalanGun: kayit.ARC_MUAYENE_KALAN_GUN ?? null,
  egzozTarihi: formTarihi(kayit.ARC_EGZOS_TARIH),
  egzozKalanGun: kayit.ARC_EGZOS_KALAN_GUN ?? null,
  vergiTarihi: formTarihi(kayit.ARC_VERGI_TARIH),
  vergiKalanGun: kayit.ARC_VERGI_KALAN_GUN ?? null,
  sozlesmeTarihi: formTarihi(kayit.ARC_SOZLESME_TARIH),
});

/** Ruhsat alanlari -> SaveAracRuhsat govdesi. */
export const ruhsatGovdesi = (veri) => ({
  ARC_MAKINE_ID: veri.makineId,
  TB_ARAC_ID: veri.aracId,
  ARC_PLAKA: veri.ruhsatPlaka,
  ARC_RUHSAT_SAHIP_KOD_ID: veri.ruhsatSahipID,
  ARC_RUHSAT_ARAC_SINIFI: veri.ruhsatAracSinifi,
  ARC_RUHSAT_IL_ID: veri.ruhsatIlID,
  ARC_RUHSAT_ILCE_ID: veri.ruhsatIlceID,
  ARC_RUHSAT_BELGE_SERI_NO: veri.ruhsatBelgeSeriNo,
  ARC_RUHSAT_TESCIL_NO: veri.ruhsatTescilNo,
  ARC_RUHSAT_TESCIL_TARIH: apiTarihi(veri.ruhsatTescilTarihi),
  ARC_RUHSAT_TRAFIK_CIKIS_TARIH: apiTarihi(veri.ruhsatIlkTescilTarihi),
  ARC_RUHSAT_TICARI_ADI: veri.ruhsatTicariAdi,
  ARC_RUHSAT_ARAC_CINSI_KOD_ID: veri.ruhsatAracCinsiID,
  ARC_RUHSAT_KULLANIM_AMACI: veri.ruhsatKullanimAmaci,
  ARC_RUHSAT_ISTIAP_HADDI: veri.ruhsatIstiapHaddi,
  ARC_RUHSAT_ROMORK_ISTIAP_HADDI: veri.ruhsatRomorkIstiapHaddi,
  ARC_RUHSAT_KOLTUK_SAYISI: veri.ruhsatKoltukSayisi,
  ARC_RUHSAT_AYAKTA_YOLCU_SAYISI: veri.ruhsatAyaktaYolcuSayisi,
  ARC_MUAYENE_TARIH: apiTarihi(veri.muayeneTarihi),
  ARC_EGZOS_TARIH: apiTarihi(veri.egzozTarihi),
  ARC_VERGI_TARIH: apiTarihi(veri.vergiTarihi),
  ARC_SOZLESME_TARIH: apiTarihi(veri.sozlesmeTarihi),
});
