import React from "react";
import { Tag, Progress } from "antd";

export const buildInitialColumns = ({ onRowClick, formatDate, formatTime, hexToRGBA, statusTag, ozelAlanlar, label, handleIsTalepCellClick }) => [
    {
      title: "İş Emri No",
      dataIndex: "ISM_ISEMRI_NO",
      key: "ISM_ISEMRI_NO",
      width: 120,
      ellipsis: true,
      visible: true,
      render: (text, record) => <a onClick={() => onRowClick(record)}>{text}</a>,
      sorter: true,
    },
    {
      title: "Tarih",
      dataIndex: "ISM_DUZENLEME_TARIH",
      key: "ISM_DUZENLEME_TARIH",
      width: 110,
      ellipsis: true,
      sorter: true,
      visible: true,
      render: (text) => formatDate(text),
    },
    {
      title: "Saat",
      dataIndex: "ISM_DUZENLEME_SAAT",
      key: "ISM_DUZENLEME_SAAT",
      width: 90,
      ellipsis: true,
      sorter: true,
      visible: true,
      render: (text) => formatTime(text),
    },
    {
      title: "İş Emri Tipi",
      dataIndex: "ISM_TIP",
      key: "ISM_TIP",
      width: 180,
      ellipsis: true,
      visible: true,
      sorter: true,
      render: (text, record) => (
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            height: "100%",
          }}
        >
          <Tag
            style={{
              display: "inline-flex",
              alignItems: "center",
              margin: 0,
              padding: "0 8px",
              lineHeight: "20px",
              backgroundColor: hexToRGBA(record.ISM_TIP_RENK ? record.ISM_TIP_RENK : "#000000", 0.2),
              border: `1.2px solid ${hexToRGBA(record.ISM_TIP_RENK ? record.ISM_TIP_RENK : "#000000", 0.7)}`,
              color: record.ISM_TIP_RENK ? record.ISM_TIP_RENK : "#000000",
            }}
          >
            {text}
          </Tag>
        </div>
      ),
    },
    {
      title: "Konu",
      dataIndex: "ISM_KONU",
      key: "ISM_KONU",
      width: 300,
      ellipsis: true,
      sorter: true,
      visible: true,
      render: (text, record) => <a onClick={() => onRowClick(record)}>{text}</a>,
    },
    {
      title: "Durum",
      dataIndex: "ISM_DURUM",
      key: "ISM_DURUM",
      width: 120,
      ellipsis: true,
      visible: true,
      sorter: true,
      render: (text, record) => {
        const circleStyle = {
          backgroundColor: record.ISM_KAPATILDI ? "red" : "green",
          borderRadius: "50%",
          display: "inline-block",
          width: "10px",
          height: "10px",
        };
        return (
          <div>
            <span style={circleStyle}></span>
            <span style={{ marginLeft: "5px" }}>{text}</span>
          </div>
        );
      },
    },
    {
      title: "Onay Durumu",
      dataIndex: "ISM_ONAY_DURUM",
      key: "ISM_ONAY_DURUM",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
      render: (_, record) => {
        const validStatuses = [1, 2, 3];
        if (validStatuses.includes(record.ISM_ONAY_DURUM)) {
          const { color, text } = statusTag(record.ISM_ONAY_DURUM);
          return (
            <div
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                height: "100%",
              }}
            >
              <Tag
                style={{
                  display: "inline-flex",
                  alignItems: "center",
                  justifyContent: "center",
                  margin: 0,
                  padding: "0 8px",
                  lineHeight: "20px",
                  backgroundColor: hexToRGBA(color, 0.2),
                  border: `1.2px solid ${hexToRGBA(color, 0.7)}`,
                  color: color,
                }}
              >
                {text}
              </Tag>
            </div>
          );
        }
        return null;
      },
    },
    {
      title: "Lokasyon",
      dataIndex: "ISM_LOKASYON",
      key: "ISM_LOKASYON",
      width: 200,
      ellipsis: true,
      sorter: true,
      visible: true,
    },
    {
      title: "Makine Kodu",
      dataIndex: "MKN_KOD",
      key: "MKN_KOD",
      width: 150,
      sorter: true,
      ellipsis: true,
      visible: true,
    },
    {
      title: "Makine Tanımı",
      dataIndex: "MKN_TANIM",
      key: "MKN_TANIM",
      width: 300,
      sorter: true,
      ellipsis: true,
      visible: true,
    },
    {
      title: "Planlanan Başlama Tarihi",
      dataIndex: "ISM_PLAN_BASLAMA_TARIH",
      key: "ISM_PLAN_BASLAMA_TARIH",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
      render: (text) => formatDate(text),
    },
    {
      title: "Planlanan Başlama Saati",
      dataIndex: "ISM_PLAN_BASLAMA_SAAT",
      key: "ISM_PLAN_BASLAMA_SAAT",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
      render: (text) => formatTime(text),
    },
    {
      title: "Planlanan Bitiş Tarihi",
      dataIndex: "ISM_PLAN_BITIS_TARIH",
      key: "ISM_PLAN_BITIS_TARIH",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
      render: (text) => formatDate(text),
    },
    {
      title: "Planlanan Bitiş Saati",
      dataIndex: "ISM_PLAN_BITIS_SAAT",
      key: "ISM_PLAN_BITIS_SAAT",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
      render: (text) => formatTime(text),
    },
    {
      title: "Başlama Tarihi",
      dataIndex: "ISM_BASLAMA_TARIH",
      key: "ISM_BASLAMA_TARIH",
      width: 110,
      ellipsis: true,
      sorter: true,
      visible: true,
      render: (text) => formatDate(text),
    },
    {
      title: "Başlama Saati",
      dataIndex: "ISM_BASLAMA_SAAT",
      key: "ISM_BASLAMA_SAAT",
      width: 90,
      ellipsis: true,
      sorter: true,
      visible: true,
      render: (text) => formatTime(text),
    },
    {
      title: "Bitiş Tarihi",
      dataIndex: "ISM_BITIS_TARIH",
      key: "ISM_BITIS_TARIH",
      width: 110,
      ellipsis: true,
      sorter: true,
      visible: true,
      render: (text) => formatDate(text),
    },
    {
      title: "Bitiş Saati",
      dataIndex: "ISM_BITIS_SAAT",
      key: "ISM_BITIS_SAAT",
      width: 90,
      ellipsis: true,
      sorter: true,
      visible: true,
      render: (text) => formatTime(text),
    },
    {
      title: "İş Süresi (dk.)",
      dataIndex: "ISM_SURE_CALISMA",
      key: "ISM_SURE_CALISMA",
      width: 110,
      ellipsis: true,
      sorter: true,
      visible: true,
      render: (text) => (text > 0 ? text : null),
    },
    {
      title: "Tamamlama (%)",
      dataIndex: "ISM_TAMAMLANMA_ORAN",
      key: "ISM_TAMAMLANMA_ORAN",
      width: 200,
      ellipsis: true,
      sorter: true,
      visible: true,
      render: (text) => <Progress percent={text} steps={8} />,
    },
    {
      title: "Makine Durumu",
      dataIndex: "ISM_MAKINE_DURUM",
      key: "ISM_MAKINE_DURUM",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Tipi",
      dataIndex: "MKN_TIP",
      key: "MKN_TIP",
      width: 250,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Ekipman",
      dataIndex: "ISM_EKIPMAN",
      key: "ISM_EKIPMAN",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "İş Tipi Kod",
      dataIndex: "ISM_TIP_KOD",
      key: "ISM_TIP_KOD",
      width: 250,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "İş Nedeni",
      dataIndex: "ISM_NEDEN",
      key: "ISM_NEDEN",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Atölye",
      dataIndex: "ISM_ATOLYE",
      key: "ISM_ATOLYE",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Talimat",
      dataIndex: "ISM_TALIMAT",
      key: "ISM_TALIMAT",
      width: 250,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Öncelik",
      dataIndex: "ISM_ONCELIK",
      key: "ISM_ONCELIK",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Takvim",
      dataIndex: "ISM_TAKVIM",
      key: "ISM_TAKVIM",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Masraf Merkezi",
      dataIndex: "ISM_MASRAF_MERKEZ",
      key: "ISM_MASRAF_MERKEZ",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Firma",
      dataIndex: "ISM_CARI",
      key: "ISM_CARI",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "İş Talep Kodu",
      dataIndex: "ISM_IS_TALEP_KODU",
      key: "ISM_IS_TALEP_KODU",
      width: 150,
      ellipsis: true,
      sorter: true,
      onCell: (record) => ({
        onClick: (event) => handleIsTalepCellClick(record, event),
      }),
      render: (text) => <a>{text}</a>,
      visible: false,
    },
    {
      title: "Personel",
      dataIndex: "ISM_PERSONEL_TANIM",
      key: "ISM_PERSONEL_TANIM",
      width: 180,
      ellipsis: true,
      sorter: true,
      visible: true,
    },
    {
      title: "Sayaç Değeri",
      dataIndex: "ISM_SAYAC_DEGER",
      key: "ISM_SAYAC_DEGER",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Notlar",
      dataIndex: "ISM_NOT",
      key: "ISM_NOT",
      width: 250,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Açıklama",
      dataIndex: "ISM_ACIKLAMA",
      key: "ISM_ACIKLAMA",
      width: 250,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Sonuç",
      dataIndex: "ISM_SONUC",
      key: "ISM_SONUC",
      width: 250,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Yapıldı",
      dataIndex: "ISM_YAPILDI",
      key: "ISM_YAPILDI",
      width: 250,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Bildiren",
      dataIndex: "ISM_BILDIREN",
      key: "ISM_BILDIREN",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Bildirim Tarihi",
      dataIndex: "ISM_BILDIRIM_TARIH",
      key: "ISM_BILDIRIM_TARIH",
      width: 110,
      ellipsis: true,
      sorter: true,
      visible: false,
      render: (text) => formatDate(text),
    },
    {
      title: "Bildirim Saati",
      dataIndex: "ISM_BILDIRIM_SAAT",
      key: "ISM_BILDIRIM_SAAT",
      width: 90,
      ellipsis: true,
      sorter: true,
      visible: false,
      render: (text) => formatTime(text),
    },
    {
      title: "Maliyet Malzeme",
      dataIndex: "ISM_MALIYET_MLZ",
      key: "ISM_MALIYET_MLZ",
      width: 120,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Maliyet Personel",
      dataIndex: "ISM_MALIYET_PERSONEL",
      key: "ISM_MALIYET_PERSONEL",
      width: 120,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Maliyet Duruş",
      dataIndex: "ISM_MALIYET_DURUS",
      key: "ISM_MALIYET_DURUS",
      width: 120,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Maliyet Dış Servis",
      dataIndex: "ISM_MALIYET_DISSERVIS",
      key: "ISM_MALIYET_DISSERVIS",
      width: 120,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Maliyet Diğer",
      dataIndex: "ISM_MALIYET_DIGER",
      key: "ISM_MALIYET_DIGER",
      width: 120,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Maliyet Toplam",
      dataIndex: "ISM_MALIYET_TOPLAM",
      key: "ISM_MALIYET_TOPLAM",
      width: 120,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: <div>{ozelAlanlar && ozelAlanlar.OZL_OZEL_ALAN_1 ? ozelAlanlar.OZL_OZEL_ALAN_1 : label && label.OZL_OZEL_ALAN_1}</div>,
      dataIndex: "ISM_OZEL_ALAN_1",
      key: "ISM_OZEL_ALAN_1",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: <div>{ozelAlanlar && ozelAlanlar.OZL_OZEL_ALAN_2 ? ozelAlanlar.OZL_OZEL_ALAN_2 : label && label.OZL_OZEL_ALAN_2}</div>,
      dataIndex: "ISM_OZEL_ALAN_2",
      key: "ISM_OZEL_ALAN_2",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: <div>{ozelAlanlar && ozelAlanlar.OZL_OZEL_ALAN_3 ? ozelAlanlar.OZL_OZEL_ALAN_3 : label && label.OZL_OZEL_ALAN_3}</div>,
      dataIndex: "ISM_OZEL_ALAN_3",
      key: "ISM_OZEL_ALAN_3",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: <div>{ozelAlanlar && ozelAlanlar.OZL_OZEL_ALAN_4 ? ozelAlanlar.OZL_OZEL_ALAN_4 : label && label.OZL_OZEL_ALAN_4}</div>,
      dataIndex: "ISM_OZEL_ALAN_4",
      key: "ISM_OZEL_ALAN_4",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: <div>{ozelAlanlar && ozelAlanlar.OZL_OZEL_ALAN_5 ? ozelAlanlar.OZL_OZEL_ALAN_5 : label && label.OZL_OZEL_ALAN_5}</div>,
      dataIndex: "ISM_OZEL_ALAN_5",
      key: "ISM_OZEL_ALAN_5",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: <div>{ozelAlanlar && ozelAlanlar.OZL_OZEL_ALAN_6 ? ozelAlanlar.OZL_OZEL_ALAN_6 : label && label.OZL_OZEL_ALAN_6}</div>,
      dataIndex: "ISM_OZEL_ALAN_6",
      key: "ISM_OZEL_ALAN_6",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: <div>{ozelAlanlar && ozelAlanlar.OZL_OZEL_ALAN_7 ? ozelAlanlar.OZL_OZEL_ALAN_7 : label && label.OZL_OZEL_ALAN_7}</div>,
      dataIndex: "ISM_OZEL_ALAN_7",
      key: "ISM_OZEL_ALAN_7",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: <div>{ozelAlanlar && ozelAlanlar.OZL_OZEL_ALAN_8 ? ozelAlanlar.OZL_OZEL_ALAN_8 : label && label.OZL_OZEL_ALAN_8}</div>,
      dataIndex: "ISM_OZEL_ALAN_8",
      key: "ISM_OZEL_ALAN_8",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: <div>{ozelAlanlar && ozelAlanlar.OZL_OZEL_ALAN_9 ? ozelAlanlar.OZL_OZEL_ALAN_9 : label && label.OZL_OZEL_ALAN_9}</div>,
      dataIndex: "ISM_OZEL_ALAN_9",
      key: "ISM_OZEL_ALAN_9",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: <div>{ozelAlanlar && ozelAlanlar.OZL_OZEL_ALAN_10 ? ozelAlanlar.OZL_OZEL_ALAN_10 : label && label.OZL_OZEL_ALAN_10}</div>,
      dataIndex: "ISM_OZEL_ALAN_10",
      key: "ISM_OZEL_ALAN_10",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: <div>{ozelAlanlar && ozelAlanlar.OZL_OZEL_ALAN_11 ? ozelAlanlar.OZL_OZEL_ALAN_11 : label && label.OZL_OZEL_ALAN_11}</div>,
      dataIndex: "ISM_OZEL_ALAN_11",
      key: "ISM_OZEL_ALAN_11",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: <div>{ozelAlanlar && ozelAlanlar.OZL_OZEL_ALAN_12 ? ozelAlanlar.OZL_OZEL_ALAN_12 : label && label.OZL_OZEL_ALAN_12}</div>,
      dataIndex: "ISM_OZEL_ALAN_12",
      key: "ISM_OZEL_ALAN_12",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: <div>{ozelAlanlar && ozelAlanlar.OZL_OZEL_ALAN_13 ? ozelAlanlar.OZL_OZEL_ALAN_13 : label && label.OZL_OZEL_ALAN_13}</div>,
      dataIndex: "ISM_OZEL_ALAN_13",
      key: "ISM_OZEL_ALAN_13",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: <div>{ozelAlanlar && ozelAlanlar.OZL_OZEL_ALAN_14 ? ozelAlanlar.OZL_OZEL_ALAN_14 : label && label.OZL_OZEL_ALAN_14}</div>,
      dataIndex: "ISM_OZEL_ALAN_14",
      key: "ISM_OZEL_ALAN_14",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: <div>{ozelAlanlar && ozelAlanlar.OZL_OZEL_ALAN_15 ? ozelAlanlar.OZL_OZEL_ALAN_15 : label && label.OZL_OZEL_ALAN_15}</div>,
      dataIndex: "ISM_OZEL_ALAN_15",
      key: "ISM_OZEL_ALAN_15",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: <div>{ozelAlanlar && ozelAlanlar.OZL_OZEL_ALAN_16 ? ozelAlanlar.OZL_OZEL_ALAN_16 : label && label.OZL_OZEL_ALAN_16}</div>,
      dataIndex: "ISM_OZEL_ALAN_16",
      key: "ISM_OZEL_ALAN_16",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: <div>{ozelAlanlar && ozelAlanlar.OZL_OZEL_ALAN_17 ? ozelAlanlar.OZL_OZEL_ALAN_17 : label && label.OZL_OZEL_ALAN_17}</div>,
      dataIndex: "ISM_OZEL_ALAN_17",
      key: "ISM_OZEL_ALAN_17",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: <div>{ozelAlanlar && ozelAlanlar.OZL_OZEL_ALAN_18 ? ozelAlanlar.OZL_OZEL_ALAN_18 : label && label.OZL_OZEL_ALAN_18}</div>,
      dataIndex: "ISM_OZEL_ALAN_18",
      key: "ISM_OZEL_ALAN_18",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: <div>{ozelAlanlar && ozelAlanlar.OZL_OZEL_ALAN_19 ? ozelAlanlar.OZL_OZEL_ALAN_19 : label && label.OZL_OZEL_ALAN_19}</div>,
      dataIndex: "ISM_OZEL_ALAN_19",
      key: "ISM_OZEL_ALAN_19",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: <div>{ozelAlanlar && ozelAlanlar.OZL_OZEL_ALAN_20 ? ozelAlanlar.OZL_OZEL_ALAN_20 : label && label.OZL_OZEL_ALAN_20}</div>,
      dataIndex: "ISM_OZEL_ALAN_20",
      key: "ISM_OZEL_ALAN_20",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Plaka",
      dataIndex: "ISM_MAKINE_PLAKA",
      key: "ISM_MAKINE_PLAKA",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Maliyet KDV",
      dataIndex: "ISM_MALIYET_KDV",
      key: "ISM_MALIYET_KDV",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Maliyet İndirim",
      dataIndex: "ISM_MALIYET_INDIRIM",
      key: "ISM_MALIYET_INDIRIM",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Planlanan Maliyet Malzeme",
      dataIndex: "ISM_MALIYET_PLAN_MLZ",
      key: "ISM_MALIYET_PLAN_MLZ",
      width: 170,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Planlanan Maliyet Personel",
      dataIndex: "ISM_MALIYET_PLAN_PERSONEL",
      key: "ISM_MALIYET_PLAN_PERSONEL",
      width: 170,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Planlanan Maliyet Duruş",
      dataIndex: "ISM_MALIYET_PLAN_DURUS",
      key: "ISM_MALIYET_PLAN_DURUS",
      width: 170,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Planlanan Maliyet Dış Servis",
      dataIndex: "ISM_MALIYET_PLAN_DISSERVIS",
      key: "ISM_MALIYET_PLAN_DISSERVIS",
      width: 190,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Planlanan Maliyet Diğer",
      dataIndex: "ISM_MALIYET_PLAN_DIGER",
      key: "ISM_MALIYET_PLAN_DIGER",
      width: 170,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Planlanan Maliyet Toplam",
      dataIndex: "ISM_MALIYET_PLAN_TOPLAM",
      key: "ISM_MALIYET_PLAN_TOPLAM",
      width: 190,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Müdahale Süresi Lojistik",
      dataIndex: "ISM_SURE_MUDAHALE_LOJISTIK",
      key: "ISM_SURE_MUDAHALE_LOJISTIK",
      width: 190,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Müdahale Süresi Seyahat",
      dataIndex: "ISM_SURE_MUDAHALE_SEYAHAT",
      key: "ISM_SURE_MUDAHALE_SEYAHAT",
      width: 190,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Müdahale Süresi Onay",
      dataIndex: "ISM_SURE_MUDAHALE_ONAY",
      key: "ISM_SURE_MUDAHALE_ONAY",
      width: 180,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Müdahale Süresi Diğer",
      dataIndex: "ISM_SURE_MUDAHALE_DIGER",
      key: "ISM_SURE_MUDAHALE_DIGER",
      width: 180,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Bekleme Süresi",
      dataIndex: "ISM_SURE_BEKLEME",
      key: "ISM_SURE_BEKLEME",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Toplam Süre",
      dataIndex: "ISM_SURE_TOPLAM",
      key: "ISM_SURE_TOPLAM",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "İşçilik Süresi",
      dataIndex: "ISM_SURE_ISCILIK",
      key: "ISM_SURE_ISCILIK",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Planlanan Talep Süresi",
      dataIndex: "ISM_SURE_PLAN_TALEP",
      key: "ISM_SURE_PLAN_TALEP",
      width: 190,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Planlanan Müdahale Süresi",
      dataIndex: "ISM_SURE_PLAN_MUDAHALE",
      key: "ISM_SURE_PLAN_MUDAHALE",
      width: 200,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Planlanan Çalışma Süresi",
      dataIndex: "ISM_SURE_PLAN_CALISMA",
      key: "ISM_SURE_PLAN_CALISMA",
      width: 190,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Planlanan Duruş Süresi",
      dataIndex: "ISM_SURE_PLAN_DURUS",
      key: "ISM_SURE_PLAN_DURUS",
      width: 190,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Planlanan Bekleme Süresi",
      dataIndex: "ISM_SURE_PLAN_BEKLEME",
      key: "ISM_SURE_PLAN_BEKLEME",
      width: 200,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Planlanan Toplam Süre",
      dataIndex: "ISM_SURE_PLAN_TOPLAM",
      key: "ISM_SURE_PLAN_TOPLAM",
      width: 200,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Planlanan Müdahale Süresi Lojistik",
      dataIndex: "ISM_SURE_PLAN_MUDAHALE_LOJISTIK",
      key: "ISM_SURE_PLAN_MUDAHALE_LOJISTIK",
      width: 240,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Planlanan Müdahale Süresi Seyahat",
      dataIndex: "ISM_SURE_PLAN_MUDAHALE_SEYAHAT",
      key: "ISM_SURE_PLAN_MUDAHALE_SEYAHAT",
      width: 240,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Planlanan Müdahale Süresi Onay",
      dataIndex: "ISM_SURE_PLAN_MUDAHALE_ONAY",
      key: "ISM_SURE_PLAN_MUDAHALE_ONAY",
      width: 220,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Planlanan Müdahale Süresi Diğer",
      dataIndex: "ISM_SURE_PLAN_MUDAHALE_DIGER",
      key: "ISM_SURE_PLAN_MUDAHALE_DIGER",
      width: 220,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Kapandı",
      dataIndex: "ISM_KAPATILDI",
      key: "ISM_KAPATILDI",
      width: 120,
      ellipsis: true,
      sorter: true,
      visible: false,
      render: (value) => (value ? "Evet" : "Hayır"),
    },
    {
      title: "Puan",
      dataIndex: "ISM_PUAN",
      key: "ISM_PUAN",
      width: 120,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "İptal Açıklaması",
      dataIndex: "ISM_IPTAL_ACIKLAMA",
      key: "ISM_IPTAL_ACIKLAMA",
      width: 250,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Durum Açıklaması",
      dataIndex: "ISM_DURUM_ACIKLAMA",
      key: "ISM_DURUM_ACIKLAMA",
      width: 250,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "İş Tipi",
      dataIndex: "ISM_IS_TIP",
      key: "ISM_IS_TIP",
      width: 180,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "İş Bildiren",
      dataIndex: "ISM_IS_BILDIREN",
      key: "ISM_IS_BILDIREN",
      width: 170,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "İş Tarihi",
      dataIndex: "ISM_IS_TARIH",
      key: "ISM_IS_TARIH",
      width: 110,
      ellipsis: true,
      sorter: true,
      visible: false,
      render: (text) => formatDate(text),
    },
    {
      title: "İş Saati",
      dataIndex: "ISM_IS_SAAT",
      key: "ISM_IS_SAAT",
      width: 90,
      ellipsis: true,
      sorter: true,
      visible: false,
      render: (text) => formatTime(text),
    },
    {
      title: "Referans No",
      dataIndex: "ISM_REFERANS_NO",
      key: "ISM_REFERANS_NO",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "İş Sonucu",
      dataIndex: "ISM_IS_SONUC",
      key: "ISM_IS_SONUC",
      width: 200,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Sözleşme",
      dataIndex: "ISM_SOZLESME",
      key: "ISM_SOZLESME",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "İş Tipi Tanımı",
      dataIndex: "ISM_TIP_TANIM",
      key: "ISM_TIP_TANIM",
      width: 200,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Proje",
      dataIndex: "ISM_PROJE",
      key: "ISM_PROJE",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Departman",
      dataIndex: "ISM_DEPARTMAN",
      key: "ISM_DEPARTMAN",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Sonuç Kodu",
      dataIndex: "ISM_SONUC_KOD",
      key: "ISM_SONUC_KOD",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Malzeme",
      dataIndex: "ISM_MALZEME",
      key: "ISM_MALZEME",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Personel Kod",
      dataIndex: "ISM_PERSONEL",
      key: "ISM_PERSONEL",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Duruş",
      dataIndex: "ISM_DURUS",
      key: "ISM_DURUS",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "İptal Onay Personel",
      dataIndex: "ISM_IPTAL_ONAY_PERSONEL",
      key: "ISM_IPTAL_ONAY_PERSONEL",
      width: 200,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "İptal Nedeni",
      dataIndex: "ISM_IPTAL_NEDEN",
      key: "ISM_IPTAL_NEDEN",
      width: 220,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Yapılamama Nedeni",
      dataIndex: "ISM_YAPILAMAMA_NEDEN",
      key: "ISM_YAPILAMAMA_NEDEN",
      width: 220,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Oluşturma Tarihi",
      dataIndex: "ISM_OLUSTURMA_TARIH",
      key: "ISM_OLUSTURMA_TARIH",
      width: 200,
      ellipsis: true,
      sorter: true,
      visible: false,
      render: (text) => formatDate(text),
    },
    {
      title: "Değiştirme Tarihi",
      dataIndex: "ISM_DEGISTIRME_TARIH",
      key: "ISM_DEGISTIRME_TARIH",
      width: 200,
      ellipsis: true,
      sorter: true,
      visible: false,
      render: (text) => formatDate(text),
    },
    {
      title: "İş Talep Grup",
      dataIndex: "IST_GRUP",
      key: "IST_GRUP",
      width: 170,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "İş Talep Kod",
      dataIndex: "IST_KOD",
      key: "IST_KOD",
      width: 170,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "İş Talep Tanım",
      dataIndex: "IST_TANIM",
      key: "IST_TANIM",
      width: 200,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Toplam Duruş Süresi",
      dataIndex: "TOPLAM_DURUS_SURE",
      key: "TOPLAM_DURUS_SURE",
      width: 190,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Masraf Merkezi (Genel)",
      dataIndex: "MASRAF_MERKEZI",
      key: "MASRAF_MERKEZI",
      width: 190,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Marka",
      dataIndex: "MKN_MARKA",
      key: "MKN_MARKA",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Model",
      dataIndex: "MKN_MODEL",
      key: "MKN_MODEL",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Kategori",
      dataIndex: "MKN_KATEGORI",
      key: "MKN_KATEGORI",
      width: 170,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Aktif",
      dataIndex: "MKN_AKTIF",
      key: "MKN_AKTIF",
      width: 150,
      ellipsis: true,
      sorter: true,
      visible: false,
      render: (value) => (value ? "Evet" : "Hayır"),
    },
    {
      title: "Makine Özel Alan 1",
      dataIndex: "MKN_OZEL_ALAN_1",
      key: "MKN_OZEL_ALAN_1",
      width: 170,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Özel Alan 2",
      dataIndex: "MKN_OZEL_ALAN_2",
      key: "MKN_OZEL_ALAN_2",
      width: 170,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Özel Alan 3",
      dataIndex: "MKN_OZEL_ALAN_3",
      key: "MKN_OZEL_ALAN_3",
      width: 170,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Özel Alan 4",
      dataIndex: "MKN_OZEL_ALAN_4",
      key: "MKN_OZEL_ALAN_4",
      width: 170,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Özel Alan 5",
      dataIndex: "MKN_OZEL_ALAN_5",
      key: "MKN_OZEL_ALAN_5",
      width: 170,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Özel Alan 6",
      dataIndex: "MKN_OZEL_ALAN_6",
      key: "MKN_OZEL_ALAN_6",
      width: 170,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Özel Alan 7",
      dataIndex: "MKN_OZEL_ALAN_7",
      key: "MKN_OZEL_ALAN_7",
      width: 170,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Özel Alan 8",
      dataIndex: "MKN_OZEL_ALAN_8",
      key: "MKN_OZEL_ALAN_8",
      width: 170,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Özel Alan 9",
      dataIndex: "MKN_OZEL_ALAN_9",
      key: "MKN_OZEL_ALAN_9",
      width: 170,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Özel Alan 10",
      dataIndex: "MKN_OZEL_ALAN_10",
      key: "MKN_OZEL_ALAN_10",
      width: 180,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Özel Alan 11",
      dataIndex: "MKN_OZEL_ALAN_11",
      key: "MKN_OZEL_ALAN_11",
      width: 180,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Özel Alan 12",
      dataIndex: "MKN_OZEL_ALAN_12",
      key: "MKN_OZEL_ALAN_12",
      width: 180,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Özel Alan 13",
      dataIndex: "MKN_OZEL_ALAN_13",
      key: "MKN_OZEL_ALAN_13",
      width: 180,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Özel Alan 14",
      dataIndex: "MKN_OZEL_ALAN_14",
      key: "MKN_OZEL_ALAN_14",
      width: 180,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Özel Alan 15",
      dataIndex: "MKN_OZEL_ALAN_15",
      key: "MKN_OZEL_ALAN_15",
      width: 180,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Özel Alan 16",
      dataIndex: "MKN_OZEL_ALAN_16",
      key: "MKN_OZEL_ALAN_16",
      width: 180,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Özel Alan 17",
      dataIndex: "MKN_OZEL_ALAN_17",
      key: "MKN_OZEL_ALAN_17",
      width: 180,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Özel Alan 18",
      dataIndex: "MKN_OZEL_ALAN_18",
      key: "MKN_OZEL_ALAN_18",
      width: 180,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Özel Alan 19",
      dataIndex: "MKN_OZEL_ALAN_19",
      key: "MKN_OZEL_ALAN_19",
      width: 180,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
    {
      title: "Makine Özel Alan 20",
      dataIndex: "MKN_OZEL_ALAN_20",
      key: "MKN_OZEL_ALAN_20",
      width: 180,
      ellipsis: true,
      sorter: true,
      visible: false,
    },
  ];
